spring.application.name=resource-server
server.port=9090

auth.jwt.jwks-uri=http://localhost:7070/oauth2/jwks

auth.opaque.introspection-uri=http://localhost:6060/oauth2/introspect
auth.opaque.client-id=client
auth.opaque.client-secret=secret
