spring.application.name=resource-server
server.port=9090

# Настройки нашего стартера sec-universal-starter.
# mode=both -> RS принимает И JWT, И opaque (выбор по заголовку "type"), как в ssia-ch15-ex5.
sec.security.mode=both
sec.security.jwt.jwks-uri=http://localhost:7070/oauth2/jwks
sec.security.opaque.introspection-uri=http://localhost:6060/oauth2/introspect
sec.security.opaque.client-id=client
sec.security.opaque.client-secret=secret
